### ISSUE TITLE
Biopac question

### ISSUE THREAD

**Issue by Isabelle-Simard** [mtl-brainhack-school-2019/ecg_pupillometry_pipeline_kaufmann#6]
Very cool project!

I might have a few questions for you regarding the Biopac kit. My lab just got one and we are having issues. How familiar are you with Biopac?

**Comment by kaufmannPolyMtl** [comment]
I can relate. We only borrowed ours and only have a limited license. One of the resulting problems is that we have to align the biopac data and other sensor measurements manually or via the pipeline that I'm working on here. Feel free to talk to me about the Biopac. Cheers.
